In [15]:
#Task 01: Merge Lineup
import numpy as np
def mergeLineup(pokemon_1,pokemon_2):
  sum_list = np.zeros(len(pokemon_1),dtype = int)
  lenth = (len(pokemon_1))
  s = 0
  e = lenth -1
  for i in range(lenth):
    if pokemon_1[i] == None :
      pokemon_1[i]= 0
    if pokemon_2[i] == None :
      pokemon_2[i]= 0
  while s < lenth :
    sum_list[s]  = pokemon_1[s] + pokemon_2[e]
    s += 1
    e -= 1
  return sum_list

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
print(mergeLineup(pokemon_1, pokemon_2))


[ 4 17  6 27  2]


In [ ]:
# Task 02: Discard Cards
import numpy as np

def discardCards(cards,t):
  print(cards)

  new_cards = np.zeros(len(cards),dtype=int)


  flg = False
  for i in range(len(cards)):
    if cards[i] == t and flg == False:
      new_cards[i] = 0
      flg = True

    elif cards[i] == t and flg == True:
      new_cards[i] = t
      flg = False


    else:
      new_cards[i] = cards[i]

  # print(new_cards)
  temp = None
  for i in range (len(new_cards)):
    for i in range (len(new_cards)-1):
      if new_cards[i] == 0:
        temp = new_cards[i]
        new_cards[i] = new_cards[i+1]
        new_cards[i+1] = temp
  return new_cards
cards = np.array([5,9,3,11,6,3,3,3,3,3,4,0,0])
print(discardCards(cards, t = 3))

[ 5  9  3 11  6  3  3  3  3  3  4  0  0]
[ 5  9 11  6  3  3  3  4  0  0  0  0  0]


In [ ]:
#Task 03: Decryption Process
def decrypt_matrix(matrix):

  r = len(matrix)
  c = len(matrix[0])

  column_sum = np.zeros(c,dtype = int)
  for column in range (c):
    sum = 0
    for row in range (r):
      sum += matrix[row][column]
    column_sum[column] = sum

  result_array = np.zeros(len(column_sum)-1,dtype = int)
  for i in range (len(result_array)-1):
    result_array[i]   =  column_sum[i+1] - column_sum[i]
    result_array[i+1] =  column_sum[i+2] -  column_sum[i+1]

  return (result_array)
matrix = np.array([
[1, 3, 1],
[6, 4, 2],
[5, 1, 7],
[9, 3, 3],
[8, 5, 4]
  ])
returned_array=decrypt_matrix(matrix)
print(returned_array)

[29 16 17]
[-13   1]


In [ ]:
# Task 04: Zigzag Walk
import numpy as np
def walk_zigzag(floor):
  flg = True
  lenth_of_row = len(floor)
  our_row = ""
  if (lenth_of_row % 2 == 0 ):
    our_row =  "EVEN"
  if (lenth_of_row % 2 != 0 ):
    our_row =  "ODD"
  for i in range (len(floor[0])):
    if flg == True :
      for j in range(0,len(floor),2):
        print(floor[j][i],end=" ")
      flg = False
      print()
    elif our_row == "ODD" and flg == False:
      for c in range (-2,-len(floor)-1,-2):
        print(floor[c][i],end=" ")
      flg = True
      print()
    elif our_row == "EVEN" and flg == False:
      for c in range (-1,-len(floor)-1,-2):
        print(floor[c][i],end=" ")
      flg = True
      print()
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                    ['7' , '2' , '1' , '9' , '3'],
                    ['9' , '0' , '7' , '5' , '8'],
                    ['2' , '1' , '3' , '4' , '0'],
                    ['1' , '4' , '2' , '8' , '6'],
                    ['6' , '7' , '8' ,'9'  , '1']])
# print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)

#This should print
#3 9 1
#7 1 2
#4 7 2
#9 4 9
#1 8 6

Walking Sequence:
3 9 1 
7 1 2 
4 7 2 
9 4 9 
1 8 6 


In [16]:
# Task 05: Row Rotation Policy of BRACU Classroom
import numpy as np
def row_rotation(exam_week, seat_status):
    exam_week = exam_week % len(seat_status)
    print(exam_week)
    for s in range(exam_week - 1):

        temp = [None] * len(seat_status[0])
        for j in range(len(seat_status[0])):
            temp[j] = seat_status[len(seat_status) - 1][j]

        for i in range(len(seat_status) - 1, 0, -1):
            for j in range(len(seat_status[i])):
                seat_status[i][j] = seat_status[i - 1][j]


        for j in range(len(temp)):
            seat_status[0][j] = temp[j]

    print("Seat status after rotations:")
    print(seat_status)


    for i in range(len(seat_status)):
        if "AA" in seat_status[i]:
            return i +1


seat_status = np.array([
    ['A', 'B', 'C', 'D', 'E'],
    ['F', 'G', 'H', 'I', 'J'],
    ['K', 'L', 'M', 'N', 'O'],
    ['P', 'Q', 'R', 'S', 'T'],
    ['U', 'V', 'W', 'X', 'Y'],
    ['ZZ', 'AA', 'BB', 'CC', 'DD']
])
exam_week = 3
row_number = row_rotation(exam_week, seat_status)
print(f'Your friend AA will be on row {row_number}')


3
Seat status after rotations:
[['U' 'V' 'W' 'X' 'Y']
 ['ZZ' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']]
Your friend AA will be on row 2


In [18]:
#Task 06: Matrix Compression
import numpy as np
def compress_matrix(matrix):

  new_matrix_column = int(len(matrix[0]) / 2)
  new_matrix_row = int(len(matrix) / 2)
  number_of_total_elements = len(matrix) * len(matrix[0])
  new_array = np.zeros(int(number_of_total_elements / 4), dtype=object)
  blank_matrix = new_array.reshape(new_matrix_row, new_matrix_column)
  sum1 = 0
  for r1 in range(new_matrix_row):
      for c1 in range (new_matrix_column):
          sum1 += matrix[r1][c1]
          blank_matrix[0][0] = sum1
  sum2 = 0
  for r2 in range(new_matrix_row):
      for c2 in range (new_matrix_column, new_matrix_column*2):
          sum2 += matrix[r2][c2]
          blank_matrix[0][1] = sum2
  sum3 = 0
  for r3 in range(new_matrix_row,new_matrix_row*2):
      for c3 in range (new_matrix_column):
          sum3 += matrix[r3][c3]
          blank_matrix[1][0] = sum3
  sum4 = 0
  for r4 in range(new_matrix_row,new_matrix_row*2):
      for c4 in range (new_matrix_column, new_matrix_column*2):
          sum4 += matrix[r4][c4]
          blank_matrix[1][1] = sum4

  return (blank_matrix)
matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])

returned_array=compress_matrix(matrix)
print(returned_array)
  #   [ 1,2,   3, 4],
  #   [ 5,6,   7, 8],
  #   [ 1,3,   5, 2],
  #   [-2,0,   6,-3]
# result
# [14 22]
# [2 10 ]

[[14 22]
 [2 10]]


In [13]:
#Task 07: Game Arena
import numpy as np
def play_game(arena):
  sum_points = 0
  rows = len(arena)
  cols = len(arena[0])
  for i in range(rows):
      for j in range(cols):
          if arena[i][j] % 50 == 0 and arena[i][j] != 0 :
              # Right cell
              if (j + 1 < cols) and arena[i][j + 1] == 2:
                  sum_points += 2
              # Bottom cell
              if i + 1 < rows and arena[i + 1][j] == 2:
                  sum_points += 2
              # Left cell
              if j - 1 >= 0 and arena[i][j - 1] == 2:
                  sum_points += 2
              # Top cell
              if i - 1 >= 0 and arena[i - 1][j] == 2:
                  sum_points += 2
  if sum_points >= 10 :
    return f'Points Gained: {sum_points}. Your team has survived the game.'
  else:
    return f'Points Gained: {sum_points}. Your team is out.'
arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])

result = play_game(arena)
print(result)


Points Gained: 6. Your team is out.


In [14]:
#Task 07: Game Arena
import numpy as np
def play_game(arena):
  sum  = 0
  for r in range (len(arena)):
    for c in range(len(arena[0])):
      if arena[r][c] % 50 == 0 and arena[r][c] != 0 :# c = 0,1,2,3
        #Right Handle
        if c < (len(arena[0])-1):# c = 0,1,2
          if arena[r][c+1] == 2:
            sum += 2
        #Left Handle
        if c > 0 :
          if arena[r][c-1] == 2:
            sum += 2
        #Down Handle
        if r < (len(arena) - 1) :#r = 0,1,2
          if arena[r+1][c] == 2:
            sum += 2
        #Up Handle
        if r > 0:
          if arena[r-1][c] == 2 :
            sum += 2
  if sum >= 10 :
    return f'Points Gained: {sum}. Your team has survived the game.'
  else:
    return f'Points Gained: {sum}. Your team is out.'


arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
result = play_game(arena)
print(result)


Points Gained: 14. Your team has survived the game.
